
server:
  port: ${SERVER_PORT:8082}

spring:
  datasource:
    url: ${DB_HOST:jdbc:h2:mem:db}
    driverClassName: org.h2.Driver
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:sa}
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  hibernate:
    ddl-auto: update
  rabbitmq:
    host: ${MQ_HOST:localhost}
    port: 5672
    username: ${MQ_USERNAME:admin}
    password: ${MQ_PASSWORD:admin}

services:
  account:
    url: ${SERVICES_ACCOUNT_URL:http://localhost:8081}
  notification:
    url: ${SERVICES_NOTIFICATION_URL:https://run.mocky.io/v3/9769bf3a-b0b6-477a-9ff5-91f63010c9d3}
